### ISSUE TITLE
Grove 光感應器修改

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#111]
(1) 圖片請換成這張
![image](https://user-images.githubusercontent.com/23159280/27415189-3fc5fe10-5738-11e7-82c6-f0bc85385b6f.png), 目前用的是舊的產品的.

(2) Grove 連接**埠**, 請從改成有土部 

(3) 請移除掉 A3, 沒有這東西

**Comment by x43x61x69** [comment]
- 1、2 已修正，又 2 是共用字串故其他 Issue 內的同樣問題皆以一併修正。(#121)
- 圖片變更的部分，由於目前圖片皆由 SeeedStudio Wiki 對應網頁取得，如非誤植（e.g. 不同型號）將不再修改，其他 Issue 適用此原則。
- 3 請見[此處](https://github.com/MediaTek-Labs/BlocklyDuino-for-LinkIt/issues/79#issuecomment-309631931)說明，目前提供的數值已包含 7697 所需，不刻意去修改來限制其他相容硬體使用。其他 Issue 類似的問題也將不再覆述理由。
- 又僅類比腳位習慣性加上前置 A，Arduino PIN 慣例上未加上普遍認知為數位腳位，這裡不認為有修改必要且不影響使用。
