### ISSUE TITLE
請移除掉外部元件這層, 並把伺服器搬下來

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#112]
![image](https://user-images.githubusercontent.com/23159280/27415353-2adb0b70-5739-11e7-813f-f8d861cbb369.png)

最下面那區就是外部元件

**Comment by x43x61x69** [comment]
Servo 為內建功能，排列優先級應在需要安裝外部函式庫的項目之上。

外部元件為需要額外安裝外部函式庫的項目，用以區別並方便統一解釋，且可減少側邊欄長度。不是每個人都有高解析度的大螢幕，筆記型電腦過多項目會讓一開始就必須要手動捲動側邊欄才能知道有哪些元件可以運動，而老師們幾乎都用筆記型電腦且非高解析度螢幕。
