### ISSUE TITLE
超音波

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#114]
![image](https://user-images.githubusercontent.com/23159280/27416198-73b26802-573e-11e7-8f4e-a867e78b50bb.png)

(1) 可使用連接埠請參考開出來的 spec.

![image](https://user-images.githubusercontent.com/23159280/27416229-a5105e7c-573e-11e7-8063-0fb6f10017b1.png)

(2) 外連接"埠"要用土字旁的
(3) 圖片請改用這張
![image](https://user-images.githubusercontent.com/23159280/27416280-0b0ef4ea-573f-11e7-9229-24769b0f0230.png)

**Comment by x43x61x69** [comment]
3 請詳述目前圖片錯誤之處，若有誤將再行開啟此 Issue。
