### ISSUE TITLE
繼電器

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#116]
(1) 請改成 D 的
![image](https://user-images.githubusercontent.com/23159280/27416615-1bf2a99e-5741-11e7-8170-ba0b712da48c.png)

![image](https://user-images.githubusercontent.com/23159280/27416678-7cf5352c-5741-11e7-97f0-036867933865.png)

(Note : 拿掉 D2, 因為不知為何初始電位是高電位, 會造成一開機就先通電)

(2) 請改用用 狀態 開/關, 不要用高低電位. (default 是關)
![image](https://user-images.githubusercontent.com/23159280/27416694-953777ee-5741-11e7-907a-4bb3f40688c8.png)

(3) 圖片請換成
![image](https://user-images.githubusercontent.com/23159280/27416659-61a5f1ee-5741-11e7-9bf6-90c88601d4e0.png)

(4) 埠

**Comment by x43x61x69** [comment]
- 2 程式碼與官方 Wiki 說明皆無 On/Off 描述，而是 HIGH/LOW，用與數位 I/O 狀態一致。
- 順帶一提，老師回饋結果顯示老師傾向使用與原始代碼相同的描述，且希望在簡單模組之外有其他更細的模組可以使用，老師希望此工具並不僅限教學，希望可以用來做日常程式編寫的簡單化操作。
- 3 請說明現有圖片有誤之處，如有誤植會再行開啟此 Issue。

**Comment by bearwbearw** [comment]
3. 統一換成 Seeed 官方的圖片 (斜視圖)
