### ISSUE TITLE
OLED Display

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#118]
(1) 外帶變數不會正確 gen 進 code

![image](https://user-images.githubusercontent.com/23159280/27420028-a79c058e-5756-11e7-9a6c-51eeab579ef9.png)

(2) 是否能限制接得上的 data type? 整數只能接整數, 浮點只能接浮點, 字串只能接字串

![image](https://user-images.githubusercontent.com/23159280/27420058-bed50340-5756-11e7-9a0c-87380239b617.png)

**Comment by x43x61x69** [comment]
- 2：No。
