### ISSUE TITLE
音調區塊無法正常生成code

### ISSUE THREAD

**Issue by smingko** [MediaTek-Labs/BlocklyDuino-for-LinkIt#126]
![d1](https://user-images.githubusercontent.com/12051006/27439960-d9ae7e36-579b-11e7-9586-2619a5e4431f.png)
![image 2](https://user-images.githubusercontent.com/12051006/27439962-da8e6802-579b-11e7-9723-c16bb4d0a86c.png)

1.在"pin"及"時長"部份無法產生正確的參數。
2.另外在時長參數後面建議是否加上單位(毫秒或秒)?

**Comment by bearwbearw** [comment]
(1) 我用最新版測試也有這問題, 請 Zw  幫忙看一下
(2) 請加個毫秒, 確實會清楚很多
