### ISSUE TITLE
Grove LED Bar 不能用

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#130]
產生的 code 有個參數順序錯誤

![image](https://user-images.githubusercontent.com/23159280/27674026-65483416-5cd6-11e7-9487-865acb7687e9.png)

下面這兩個參數順序錯誤, 應該是 (3, 2, 0)

若 block 上的是 N
則參數是 (N+1, N, 0)

![image](https://user-images.githubusercontent.com/23159280/27674047-79a895c2-5cd6-11e7-8175-04c44e57fbad.png)

**Comment by bearwbearw** [comment]
![image](https://user-images.githubusercontent.com/23159280/27812147-3233873e-609f-11e7-89e4-3eca6f196fe2.png)
好像沒改到耶

帶入的參數還是錯誤的
若是 D2, 則參數應該是 (3, 2, 0)

**Comment by x43x61x69** [comment]
#138 是在 22 小時前更新至 dev，2.9.0 是在 23 小時前發布，且此 issue 歸類在 milestone 2.10.0，不是 2.9.0。

在 2.9.3b（目前 dev 的版本）下是 `(3, 2, 0)` 沒有錯誤，請勿將以關閉的 issue 重開，有疑義請用討論的形式，有必要會再被打開。
