### ISSUE TITLE
OLED 顯示器要的文字位置要改一下

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#131]
**Codebase : playground**

Seeed 的這 library 開出來的 API 如下ㄡ
![image](https://user-images.githubusercontent.com/23159280/27674973-aba8d4b6-5cda-11e7-9565-514b1030473c.png)

目前開出來的 block 如下. 
![image](https://user-images.githubusercontent.com/23159280/27674992-c00acb76-5cda-11e7-8584-046b8646e7c8.png)

目前**傳反了**顯示位置不對.
傳進去的參數錯誤, X 應該要傳到 column, Y 應該要傳到 row.

![image](https://user-images.githubusercontent.com/23159280/27675154-7172bc34-5cdb-11e7-8942-e87f126664db.png)

![image](https://user-images.githubusercontent.com/23159280/27675149-638158e2-5cdb-11e7-8283-5348a69bffa1.png)

**討論**
看這介面要不要也改成 , 會不會比用 XY 合適. 用 XY 有點讓人 imply 是 pixel 的感覺. 但這實際上是文字輸出方格 (8x8) 的位置
設定輸出位置 列 : "   "   行 : "  "

**Comment by x43x61x69** [comment]
改用「行、列」顯示。
