### ISSUE TITLE
BLE 和 Serial 產生 code 的順序不正確

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#133]
希望能在初始化藍芽前後都印 log
![image](https://user-images.githubusercontent.com/23159280/27727747-66e7d5d8-5db2-11e7-8e06-e490690a27b5.png)

產生出的 code 都跑到後面

![image](https://user-images.githubusercontent.com/23159280/27727729-59ac02b8-5db2-11e7-9900-eb2c25f83dde.png)

**Comment by x43x61x69** [comment]
在`setup()` 區塊這是正常現象。為了防止重複定義，部分初始化 code 的生成及處理與一般性可重複的 code 不同，位置也由系統處理時自動安排且必為一般性 code 之前。如果要能夠按照順序，則必須把 block 拆成多個小部件由使用者自行依邏輯組合成對應的形式才有可能。
