### ISSUE TITLE
BLE 產生的 code 排版會少個換行

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#134]
![image](https://user-images.githubusercontent.com/23159280/27728295-35fffea8-5db4-11e7-9e2c-0b572a026fea.png)

![image](https://user-images.githubusercontent.com/23159280/27728281-2ae87180-5db4-11e7-929e-7d3cbd86710c.png)

**Comment by x43x61x69** [comment]
@bearwbearw 再次提醒請勿使用右邊的任何選單內容，會造成開發團隊排成困擾！

**Comment by bearwbearw** [comment]
got it, 所以我只要發 issue, 你們自己標....
