### ISSUE TITLE
序列埠印出無法連接數位讀取積木

### ISSUE THREAD

**Issue by smingko** [MediaTek-Labs/BlocklyDuino-for-LinkIt#148]
![image](https://user-images.githubusercontent.com/12051006/28023971-00b9a486-65c2-11e7-83c3-e2746dc43c97.png)

[序列埠印出]積木無法連接[數位讀取]積木
[類比讀取]積木則可以正常連接。

**Comment by x43x61x69** [comment]
@smingko 此問題已於 dev 內修正（_v2.11.2b_），預計週五推出的 _v2.12.0_ 正式版會修正此問題，詳見： ead26bfb30de9e2b9ff54a2792407aec0279ad77。

發生問題的原因：

`digitalRead()` 僅有 `HIGH` 與 `LOW` 兩種回傳值，在 block 上回傳值歸類為 `Boolean`；目前的 `Serial.print()` block 設計僅能接受 `Number` 與 `String`；而 `analogRead()` 回傳值為 0 - 255，為 `Number` 類，故可以串接。
