### ISSUE TITLE
存檔時, 需要限制不能有 "空格"

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#150]
Alan Wen 實際使用時, 再 BlockDuion 存了一個 "Test 1", 但到了 Arudino 打開會出現錯誤訊息.
經一些測試, Arduino 存檔時會限制檔名(也是 folder 名) 內不能有空格, 會自動轉成 underscore 

test 1 => test_1 

請再 blockldyuino 實做類似機制, 避免存檔後再 Arduino 打開會錯誤

![image](https://user-images.githubusercontent.com/23159280/28099513-9b67273c-66ef-11e7-908f-06c4dd75458f.png)

**Comment by x43x61x69** [comment]
2.12.0 將使用 regex pattern `/[^a-zA-Z0-9]+/ig, '_'` 清理檔案名稱。
