### ISSUE TITLE
Add support of compile and upload binary without open Arduino IDE

### ISSUE THREAD

**Issue by kevinchung0921** [MediaTek-Labs/BlocklyDuino-for-LinkIt#151]
It is not convenient if can not compile and upload binary directly. Please check 
[link](https://github.com/kevinchung0921/BlocklyDuino-for-LinkIt/commit/5082e54caa53f4cb015ffc9f9c872db53135b231)

**Comment by x43x61x69** [comment]
@kevinchung0921 We were aware that the original BlocklyDuino has a built-in Python script to do the background communication with the Arduino IDE.

However, for the users to fully understand and learn to code within the real IDE is the goal, so neglect the IDE layer wasn't a great way of learning for the users (some are kids). Also, asking users to install and setup the dependencies such as Python is proven to be too complicate for most of them.

So yes it can be done and might be added in the future, but will not be a default method of uploading code to the board anytime soon. I will check the code you provided and maybe add it to the dev branch.
