### ISSUE TITLE
Blockly2.11.0版本，MCS連線問題

### ISSUE THREAD

**Issue by FengChihHsu** [MediaTek-Labs/BlocklyDuino-for-LinkIt#155]
Blockly2.11.0，使用MCS、MCS Lite的Switch Control Datachannel，˙7967只有reset第一次更新資料時，可以得到資料，之後Switch Control Datachannel無法正常德到資料

**Comment by x43x61x69** [comment]
@FengChihHsu 請協助確認 v2.12.1 是否修正此問題，謝謝！

**Comment by FengChihHsu** [comment]
已修正，沒有問題，謝謝

2017年7月17日 09:07，"Zhi-Wei Cai" <notifications@github.com>寫道：
