### ISSUE TITLE
EddyStoneURL block does not generate include libraries

### ISSUE THREAD

**Issue by gasolin** [MediaTek-Labs/BlocklyDuino-for-LinkIt#157]
According to https://github.com/MediaTek-Labs/Arduino-Add-On-for-LinkIt-SDK/blob/master/middleware/third_party/arduino/hardware/arduino/mt7697/libraries/LBLE/examples/EddystoneURLAdvertisement/EddystoneURLAdvertisement.ino,

Need generate these 2 libraries

```
#include <LBLE.h>
#include <LBLEPeriphral.h>
```

**Comment by x43x61x69** [comment]
@gasolin fixed in 99f032bbe1f1acfd2e0f18d322807f4c63369b61.

**Comment by gasolin** [comment]
Thanks, I'm not familiar with BLE, but waiting `LBLE.ready()` seems also needed

```
LBLE.begin();
  while (!LBLE.ready()) {
    delay(100);
}
```

**Comment by x43x61x69** [comment]
@gasolin yes, that's correct. I'll reopen this issue.
