### ISSUE TITLE
顯示頻道產生錯誤 Class

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#17]
![image](https://cloud.githubusercontent.com/assets/23159280/26394405/74975c06-409f-11e7-9b1b-3e1bc71c73c4.png)

![image](https://cloud.githubusercontent.com/assets/23159280/26394424/8432a440-409f-11e7-95fe-7fde27e6649d.png)

顯示頻道除了 整數類型, 其他都還是生成 Controller Class. 應該是 Display

**Comment by r04922159** [comment]
已修正
