### ISSUE TITLE
音調積木沒有反應

### ISSUE THREAD

**Issue by FengChihHsu** [MediaTek-Labs/BlocklyDuino-for-LinkIt#172]
你好，Blockly積木無法正常使用，無法更改聲音頻率，時間長度也無法使用，建議擺上noTone()積木。
![image](https://user-images.githubusercontent.com/30144590/32269871-ac12d72e-bf2e-11e7-8279-4432d4326768.png)

**Comment by alieonsido** [comment]
你好，不好意思現在才看到這篇issue。
不過目前實測是可以使用的，能否再詳述一下無法測試時的狀況？

如果有需要我再將此篇issue open.

[Imgur](https://i.imgur.com/1cd2YLk.png)
[Imgur](https://i.imgur.com/iaZ1ra1.png)
