### ISSUE TITLE
Com Port setting fallback to default

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#181]
選完  COM PORT , Build 完並上傳一次, COM Port 會又回原來的初始值, 第二次上傳會失敗

**Comment by pablosun** [comment]
Fixed and released in 3.0.202b

Windows 64-bit：
http://download.labs.mediatek.com/resource/blocklyduino/blocklyduino-3.0.202b-win64-ide.zip
 
Windows 32-bit:
http://download.labs.mediatek.com/resource/blocklyduino/blocklyduino-3.0.202b-win32-ide.zip
