### ISSUE TITLE
Add Linkit Remote

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#183]
[LRemote.pptx](https://github.com/MediaTek-Labs/BlocklyDuino-for-LinkIt/files/1866953/LRemote.pptx)

High level requirement~
Please feel free to modify

**Comment by pablosun** [comment]
Fixed and released in 3.0.202b

Windows 64-bit：
http://download.labs.mediatek.com/resource/blocklyduino/blocklyduino-3.0.202b-win64-ide.zip
 
Windows 32-bit:
http://download.labs.mediatek.com/resource/blocklyduino/blocklyduino-3.0.202b-win32-ide.zip
