### ISSUE TITLE
Log 在某些 狀況下, 會停止輸出到燒錄狀態, 但底層還在繼續編譯和燒錄

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#187]
![mssing log](https://user-images.githubusercontent.com/23159280/41752947-125e8976-75fd-11e8-954a-82b12cd959f6.jpg)

**Comment by bearwbearw** [comment]
通常看到都會是停在這 WMath.cpp.o 這個位置

**Comment by pablosun** [comment]
When this happens, node.js `child_process.exec` will callback `exit` event, even when the underlying `arduino_debug.exe` is actually alive and running.

Disable `verbose-build` option seems being able to avoid this issue.

**Comment by pablosun** [comment]
Workarounded in 
http://download.labs.mediatek.com/resource/blocklyduino/blocklyduino-3.0.202b-win64-ide.zip
