### ISSUE TITLE
RFID library問題

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#188]
MFRC522 library沒有放進Arduino  library導致編譯失敗

**Comment by pablosun** [comment]
煩請協助確認：
http://download.labs.mediatek.com/resource/blocklyduino/blocklyduino-3.0.202b-win64-ide.zip
應該有修正此問題。

**Comment by pablosun** [comment]
抱歉，應該是
http://mediatek.labs.sdks.us-west-2.s3.amazonaws.com/resource/blocklyduino/blocklyduino-3.0.214b-win64-ide.zip
