### ISSUE TITLE
變更Serial速度值後，Launch PuTTY serial monitor後會直接跳出亂碼

### ISSUE THREAD

**Issue by timliucode** [MediaTek-Labs/BlocklyDuino-for-LinkIt#189]
如圖所示
我將序列桿從預設的9600切換成115200並燒入後無法正確顯示資料
![2018-06-24](https://user-images.githubusercontent.com/27921307/41812248-0e083f24-7752-11e8-8fbe-6a4c2e5d82d5.png)

**Comment by pablosun** [comment]
目前需要自行調整 Putty 的 baudrate 設定，可以先參考網路上的說明文章（如：http://benjr.tw/20349）來調整 baudrate 至 115200.

**Comment by pablosun** [comment]
請下載
http://mediatek.labs.sdks.us-west-2.s3.amazonaws.com/resource/blocklyduino/blocklyduino-3.0.214b-win64-ide.zip
或
http://mediatek.labs.sdks.us-west-2.s3.amazonaws.com/resource/blocklyduino/blocklyduino-3.0.214b-win32-ide.zip

新版本(214b)當中，會根據 Serial.begin()當中的baudrate 來指定 putty.exe 的 baudrate 參數。
