### ISSUE TITLE
RFID及LCD問題

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#190]
RFID LCD 模組一起使用導致7697當機

**Comment by pablosun** [comment]
~~能否提供範例的存檔呢（XML / INO）？謝謝~~
可以重現此問題。初步研判是MFC522的預設 reset pin 會指定為 P9，而P9剛好就是 I2C 會用到的pin。

**Comment by jackjeanab** [comment]
測試時RFID依此範例接線
https://docs.labs.mediatek.com/linkit-7697-blocklyduino/a29-mfrc522-rfid-12883175.html
LCD接線
P8及P9

**Comment by jackjeanab** [comment]
![default](https://user-images.githubusercontent.com/35165571/41836596-c7de10ea-788d-11e8-8dbc-a126f976cd2a.png)

**Comment by jackjeanab** [comment]
[RFID_LCD.zip](https://github.com/MediaTek-Labs/BlocklyDuino-for-LinkIt/files/2132151/RFID_LCD.zip)

**Comment by pablosun** [comment]
煩請協助確認：
http://mediatek.labs.sdks.us-west-2.s3.amazonaws.com/resource/blocklyduino/blocklyduino-3.0.214b-win64-ide.zip
應該有修正此問題。

（新版為214b)
