### ISSUE TITLE
請新增IFTTT積木

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#192]
目前可由MCS轉發到IFTTT  如果只是需要從7697驅動IFTTT  有IFTTT積木就不用再額外設定MCS

**Comment by pablosun** [comment]
請問是指觸發 IFTTT 的 [maker channel (webhook) ](https://ifttt.com/maker_webhooks) 嗎？

**Comment by jackjeanab** [comment]
是的

Pablo Sun <notifications@github.com> 於 2018年6月27日週三 上午10:36 寫道：

**Comment by pablosun** [comment]
預計下一版本可新增 IFTTT 積木到「其他」這個分類，如下：
![image](https://user-images.githubusercontent.com/12759919/42485433-2fefeabc-842a-11e8-91c4-45c3159a6108.png)

**Comment by jackjeanab** [comment]
Great!

Pablo Sun <notifications@github.com> 於 2018年7月10日週二 上午10:15 寫道：
