### ISSUE TITLE
請新增字串連接運算積木

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#193]
例如:
String A = "ABC";
A = A  + "123"; //這個連接運算

**Comment by pablosun** [comment]
The blocks are already implemented in v2. But there are no code generation routines. We can simply add the code generation routines to:
```cpp
String() + user_input1 + user_input2 + ...
```

**Comment by pablosun** [comment]
Hi @jackjeanab ，請問這樣子的 block 是否合乎您的需求？（按「星號」可以添加新的字串）

請看圖例裡面的「串接文字」block：
![image](https://user-images.githubusercontent.com/12759919/42433523-448215ca-8382-11e8-8a10-f7814f4d7a14.png)

**Comment by jackjeanab** [comment]
OK Thank you so much!
