### ISSUE TITLE
遙控器積木問題

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#194]
使用更新文字標籤積木時  直接填入字串  編譯錯誤
![default](https://user-images.githubusercontent.com/35165571/41992373-d70d410a-7a7a-11e8-8823-ffdcc1c5a788.png)

**Comment by jackjeanab** [comment]
[error.zip](https://github.com/MediaTek-Labs/BlocklyDuino-for-LinkIt/files/2142459/error.zip)

**Comment by jackjeanab** [comment]
燒錄狀態
Launching Arduino.exe...
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
Build options changed, rebuilding all
In file included from C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\sketches\tmp\tmp.ino:9:0:

C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h: In constructor 'LRemoteClass::LRemoteClass()':

 C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h:365:7: warning: 'LRemoteClass::m_canvasColumn' will be initialized after [-Wreorder]

 int m_canvasColumn;

 ^

 C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h:364:7: warning: 'int LRemoteClass::m_canvasRow' [-Wreorder]

 int m_canvasRow;

 ^

 C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h:276:3: warning: when initialized here [-Wreorder]

 LRemoteClass()

 ^

C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h:366:17: warning: 'LRemoteClass::m_orientation' will be initialized after [-Wreorder]

 RCOrientation m_orientation;

 ^

 C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h:362:10: warning: 'String LRemoteClass::m_deviceName' [-Wreorder]

 String m_deviceName;

 ^

 C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\arduino-1.8.5\portable\packages\LinkIt\hardware\linkit_rtos\0.10.18\libraries\LRemote\src/LRemote.h:276:3: warning: when initialized here [-Wreorder]

 LRemoteClass()

 ^

 C:\Users\Jack\Downloads\blocklyduino-3.0.214b-win64-ide\BlocklyDuino3\sketches\tmp\tmp.ino: In function 'void loop()':

 tmp:58: error: 'Counting' was not declared in this scope

 label1.updateText(String(Counting));

 ^

exit status 1
Arduino.exe exited with 1 and null

**Comment by pablosun** [comment]
The code generation routine `Blockly.Arduino.linkit_lremote_update_textlabel` wrong fully remotes `"` from the generated expression
