### ISSUE TITLE
NTP and RTC issues

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#200]
有老師在問時鐘問題  他們的意見
製作RTC積木  可設定時間  讓RCT開始計時 可顯示現在時間

另外有老師問 網路校時問題 他們的意見
製作積木可抓國內NTP伺服器的時間

**Comment by pablosun** [comment]
![image](https://user-images.githubusercontent.com/12759919/42809263-cb04a7aa-89e7-11e8-9cb6-6bda07211bbf.png)

**Comment by jackjeanab** [comment]
Thank you so much!

Pablo Sun <notifications@github.com> 於 2018年7月17日週二 下午5:35 寫道：

**Comment by pablosun** [comment]
Implemented in v3.0.214b
