### ISSUE TITLE
MPU9250程式編譯出現錯誤

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#205]
![default](https://user-images.githubusercontent.com/35165571/43042957-5fb9a9fa-8dbb-11e8-94cd-b608b7ad6014.png)
編譯的錯誤訊息
Launching Arduino.exe...
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
C:\BlocklyDuino3\sketches\tmp\tmp.ino:10:29: fatal error: mpu9250_blockly.h: No such file or directory

#include <mpu9250_blockly.h>

 ^

 compilation terminated.

exit status 1
Arduino.exe exited with 1 and null

**Comment by pablosun** [comment]
Root cause: the arduino portable package does not include "mpu6050-wrapper" library.

**Comment by jackjeanab** [comment]
Yes

Pablo Sun <notifications@github.com> 於 2018年7月23日週一 下午4:52 寫道：
