### ISSUE TITLE
無法覆值

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#21]
![image](https://cloud.githubusercontent.com/assets/23159280/26396318/740a49e6-40a5-11e7-9d2a-63f037d0e10f.png)

OnOff Channel (datatype 是 bool) 
Category Channel (datatype 是 String)
String Channel (datatype 是 String)

無法覆值到正確的 datatype 上, 請討論一下要怎樣修改, 在正式修改前請先找 Bear 討論

**Comment by r04922159** [comment]
已修改
