### ISSUE TITLE
ITFFF 僅能正確傳送一次

### ISSUE THREAD

**Issue by cyrilwang** [MediaTek-Labs/BlocklyDuino-for-LinkIt#226]
使用下列積木，僅第一次能夠正確呼叫 webhook。

![ifttt error](https://user-images.githubusercontent.com/2673235/46347872-a2d7d480-c67f-11e8-839b-609d6786a5f5.png)

將產生的程式碼使用 Arduino IDE 移除註解並重新上傳後，Console 每隔10秒出現下列訊息

disconnecting from server
Hello World

**Comment by pablosun** [comment]
您好，

看來是因為 IFTTT 使用 `connection: close` 的提示的行為是不太一樣的，所以我們需要主動停止連結。在 Beta 5 的 IFTTT 產生的 code 會加上無論如何都使用 `stop()` 斷開連線的邏輯。
