### ISSUE TITLE
digitalRead積木問題

### ISSUE THREAD

**Issue by jackjeanab** [MediaTek-Labs/BlocklyDuino-for-LinkIt#227]
內建的整數變數積木item可以跟數位讀取積木合併
但變數名稱改變後就無法跟數位讀取積木合併

![default](https://user-images.githubusercontent.com/35165571/46383052-edd60400-c6e0-11e8-9877-5c628f4ee7c5.png)

**Comment by pablosun** [comment]
fix in Beta_5
