### ISSUE TITLE
感測模組下的環境感測積木無法讀取G3 的 pm2.5的數值

### ISSUE THREAD

**Issue by ufoetearth** [MediaTek-Labs/BlocklyDuino-for-LinkIt#236]
感測模組下的環境感測積木無法讀取G3 的 pm2.5的數值
讀到的都是0
且更改不同的感測器，arduino的程式碼都沒有改變
不知原因為何

**Comment by pablosun** [comment]
Hi, PMS3003/5003/7003 使用的 library 是一樣的，所以arduino的程式碼是一樣的，使用時可以注意，在 block 上面的  RX/TX 是 ”LinkIt 7697 上面的 RX/TX"，所以對應到 G3 模組時，是要 7697 RX 對 G3 TX 的。
