### ISSUE TITLE
RFID接收到時，透過IFTTT觸發傳送LINE訊息，結果通電第一次或序列埠打開第一次IFTTT都會成功觸發並傳送LINE，第二次以後都失敗，7697必須關電源重開或序列埠關掉重開，才能用。

### ISSUE THREAD

**Issue by f52233ledia** [MediaTek-Labs/BlocklyDuino-for-LinkIt#237]
![1](https://user-images.githubusercontent.com/38580476/54869609-1f00d880-4dd6-11e9-8879-094466b4948d.png)

**Comment by pablosun** [comment]
您好，

看來是因為 IFTTT 使用 `connection: close` 的提示的行為是不太一樣的，所以我們需要主動停止連結。在 Beta 5 的 IFTTT 產生的 code 會加上無論如何都使用 `stop()` 斷開連線的邏輯。
