### ISSUE TITLE
數位 IO 的 stat 翻譯沒改到

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#27]
![image](https://cloud.githubusercontent.com/assets/23159280/26431039/679ff424-4124-11e7-84f8-4911c8646b12.png)

**Comment by bearwbearw** [comment]
![image](https://cloud.githubusercontent.com/assets/23159280/26431061/8b892036-4124-11e7-8973-f7d1bce7530c.png)

**Comment by r04922159** [comment]
翻譯已改
