### ISSUE TITLE
變數的單選的下拉選單, 顯示換變成多選 

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#28]
![image](https://cloud.githubusercontent.com/assets/23159280/26431506/dede1dec-4127-11e7-88e0-c0649e72ec08.png)
點選別的之後, 勾勾應該消失

**Comment by r04922159** [comment]
這個我問題這邊沒有，不確定是什麼原因，個人猜測有可能是延遲。
然後這是 Blocklyduino 原生的東西，如果有問題的話有可能所有下拉選單都有問題。

會再繼續找看看是不是哪邊有 Bug。

**Comment by bearwbearw** [comment]
我也在找別人試試看, 有可能是我 Browser 的問題~

**Comment by x43x61x69** [comment]
我在 macOS binary 版中測試該 block 是沒有此問題的，用 Chrome 58 在 macOS 上也正常。

**Comment by pablosun** [comment]
在 Win7 - 64bit Chrome 也無法 reproduce `Version 51.0.2704.106 m (64-bit)`

**Comment by x43x61x69** [comment]
如果有復現的話再重啟，先關閉。
