### ISSUE TITLE
Add a screenshot on readme.md

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#30]
請在 readme 那放一張使用中的 screenshot, 人家一連到這 repo 一看就知道 blocklyduino 到底是啥了~

**Comment by x43x61x69** [comment]
Add in commit [#01cc907](https://github.com/MediaTek-Labs/BlocklyDuino-for-LinkIt/commit/01cc907d2a962d60a9a408f6f8b255b1425dd264).
