### ISSUE TITLE
先移掉藍芽 Central 部分

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#31]
![image](https://cloud.githubusercontent.com/assets/23159280/26432023/35a54fc6-412b-11e7-8f9a-57b3729a5833.png)
上面還有很多 central 的 block, 請移掉到剩下下面這些

![image](https://cloud.githubusercontent.com/assets/23159280/26432188/833b787c-412c-11e7-9214-6f10f279cc79.png)

**Comment by x43x61x69** [comment]
屬性從讀改成預設是讀寫，但是我們討論之後決定保留該欄位不移除，理由跟不使用型別自動化一樣，且他不去動預設就是可以任意使用。

See commit [fac3767](https://github.com/MediaTek-Labs/BlocklyDuino-for-LinkIt/commit/fac3767201feb1bb3bc6205f46868a37f0048dd9).
