### ISSUE TITLE
藍芽缺少寫入的 block

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#33]
![image](https://cloud.githubusercontent.com/assets/23159280/26432275/2cfd3904-412d-11e7-86bd-f4054a678c9c.png)

**Comment by pablosun** [comment]
藍芽寫入（設定屬性的value）的 API 有區分為兩個 Type，請評估是否要跟 MCS 寫入 API 一樣，在寫入時也要用 dropdown box 選擇「藍芽屬性的類型」是「整數」還是「字串」。

寫入API分別為：
```cpp
LBLECharacteristicInt::setValue(int value);
LBLECharacteristicString::setValue(const String& string);
```

**Comment by r04922159** [comment]
已新增，可下拉選單選整數或字串
