### ISSUE TITLE
Servo 的改進項目

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#36]
請參考以下的改進項目, 只需要剩下這些 block
![image](https://cloud.githubusercontent.com/assets/23159280/26450398/cb25025e-4189-11e7-8ef1-0853fe183546.png)

**Comment by x43x61x69** [comment]
部分修正至 dev，其餘部份交給 @alieonsido 處理。

**Comment by alieonsido** [comment]
Got it.

**Comment by alieonsido** [comment]
reference: https://www.arduino.cc/en/Reference/ServoRead

關於__myservo.read不產生attach的原因：
由於此原生的function是針對類似SG90此類**不具有回授能力的Servo**來做設計，
__myservo.read的function設計僅return回最後一次__myservo.write的值，因此**勢必得依附於Servo.write，也就是必須得跟其他的servo block做協調應用**
