### ISSUE TITLE
隨機的方塊. Min / Max 反過來

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#44]
![image](https://cloud.githubusercontent.com/assets/23159280/26619386/d457b250-4610-11e7-839d-993da5923958.png)
請改一下最大值/最小值的左右位置.
小的在左邊, 大的在右邊

**Comment by bearwbearw** [comment]
![image](https://cloud.githubusercontent.com/assets/23159280/26619386/d457b250-4610-11e7-839d-993da5923958.png)
請改一下最大值/最小值的左右位置.
小的在左邊, 大的在右邊

**Comment by x43x61x69** [comment]
Ref: #63.
