### ISSUE TITLE
修改 伺服馬達　的字串

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#45]
![image](https://cloud.githubusercontent.com/assets/23159280/26620189/5c7a4988-4614-11e7-9dc8-ea72211b2abf.png)
請在箭頭處加上 **伺服馬達** . 單一block 應該要能夠明確說明自己是屬於哪個模塊~

**Comment by x43x61x69** [comment]
Ref commit: #62.
