### ISSUE TITLE
英文 Array 修改

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#47]
![image](https://cloud.githubusercontent.com/assets/23159280/26622490/281b378e-461d-11e7-9d25-7b0edf7a0f5f.png)

**Comment by x43x61x69** [comment]
Ref: #65.

**Comment by bearwbearw** [comment]
![image](https://cloud.githubusercontent.com/assets/23159280/26716561/8a3e9506-47ac-11e7-8f6d-c917e2026507.png)
C => c
G = > g
