### ISSUE TITLE
英文 Math 字串修改

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#48]
字串原則
(1) 全都用小寫
(2) 除了縮寫字或專有名詞外 (BLE, UUID, Wi-Fi)

![image](https://cloud.githubusercontent.com/assets/23159280/26622663/bd803a0e-461d-11e7-9d2e-eda21f5661dd.png)

**Comment by x43x61x69** [comment]
Ref. #74.

**Comment by bearwbearw** [comment]
still not fix in DEV branch
