### ISSUE TITLE
英文 Text 修改

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#49]
![image](https://cloud.githubusercontent.com/assets/23159280/26622749/f1203116-461d-11e7-812d-3e3c2fa27525.png)

**Comment by x43x61x69** [comment]
Ref. #70.

**Comment by bearwbearw** [comment]
Comment out => comment out

英文的 block 的原則, 除了是專有名詞的縮寫, BLE, Wi-Fi, MCS, 其他都用小寫

**Comment by x43x61x69** [comment]
See #52.
