### ISSUE TITLE
英文 Initializes

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#51]
![image](https://cloud.githubusercontent.com/assets/23159280/26622862/6475fac4-461e-11e7-9ba6-e582957b9f26.png)

**Comment by x43x61x69** [comment]
Ref: #67.

官方文件把 `setup()` 和 `loop()` 歸類在 initialize（structure），Procedure 比較符合中文翻譯後的標題，依據 #57 原則維持英文選單項目名稱，僅修改 block 標題。

原則上中文對齊英文，除翻譯後意思難解需重新另訂稱法，英文不對中文部分做反向對齊。
