### ISSUE TITLE
英文 Time

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#56]
![image](https://cloud.githubusercontent.com/assets/23159280/26623281/d037fab8-461f-11e7-84c7-d8a41abb6176.png)

**Comment by x43x61x69** [comment]
官網有英文詳細解釋，這邊採用原始 Arduino 函數名稱，不另做修改。

僅中文因無官網解釋才做對應意思變化翻譯。
