### ISSUE TITLE
英文 wi-fi 字串

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#57]
![image](https://cloud.githubusercontent.com/assets/23159280/26623349/01f661b6-4620-11e7-9ae6-830fabc3efce.png)

**Comment by x43x61x69** [comment]
Ref: #64.

因為有很多這類大小寫的修改，規則不是很一致，這邊統一規則成：

- 一律大寫：欄位名稱採用各字首大寫（例：`Wi-Fi Password`）。
- 一律小寫：上述規定外，若該英文字為原始 Arduino 函數名稱（例：`delay()`、`setup()`）。
- 函數名稱：中文版採用對應意思翻譯函數名稱（`setup()` -> 初始化），英文採用原始 Arduino 函數名稱不更動（`millis()`、`delay()`，一律後綴括號組`()`），因使用者可以直接參照 Ardunio 官網原始英文解說。
