### ISSUE TITLE
英文 BLE Beacon 字串

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#60]
![image](https://cloud.githubusercontent.com/assets/23159280/26623714/2b718f9c-4621-11e7-9c09-6a4461255689.png)

**Comment by x43x61x69** [comment]
這邊應該是用大寫才正確。

Ref: [https://en.wikipedia.org/wiki/IBeacon#Settings](https://en.wikipedia.org/wiki/IBeacon#Settings)
