### ISSUE TITLE
v2.5.0 has two servo in the menu tree

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#76]
![image](https://cloud.githubusercontent.com/assets/23159280/26716218/2fd156fe-47ab-11e7-8b74-1ad8abb972b5.png)

**Comment by x43x61x69** [comment]
可能是先前勾到 Servo 設定內的選項造成的。目前我們這邊四台電腦（win/maxOS），在 2.5.0 & 2.6.5 都僅有一個 Servo。

我們會研究一下如何取消之前已經開啟的人如何關閉。
