### ISSUE TITLE
UUID 字串修改 (意思有錯誤的, 且符合 ZW 定義的 convention)

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#77]
Service UUID 都改成 UUID.

Service UUID 是有意義的, Charaictersitec 的 UUID 叫 service UUID 是不正確的
![image](https://user-images.githubusercontent.com/23159280/26957704-5e5d80d0-4cf9-11e7-9f61-968190f41217.png)

**Comment by x43x61x69** [comment]
對照藍牙規範，建立裝置的地方其實是可以有多個 Service UUID，裝置本身並沒有 UUID 的概念。為了避免使用者混淆，建立裝置的部分 UUID 會統一用服務 UUID（Service UUID），建立屬性的部分因為已經可以了解是屬性的 UUID，所以會改成僅有 UUID。

@r04922159

**Comment by bearwbearw** [comment]
okay, 就依照 zw 的建議修改
