### ISSUE TITLE
Servo 產生出來的 code 有錯誤

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#80]
![image](https://user-images.githubusercontent.com/23159280/27116471-0911eb5c-5104-11e7-90cd-b96800432b4b.png)

若使用 設定範圍的 attach 積木, 就不應該還有 _myservo10.attach(10), 會把 _myservo10.attach (10,620,2700) 的設定值 override 掉, 會變成無用

**Comment by bearwbearw** [comment]
這會造成 Servo 無法設定範圍, 會超出正確使用範圍有可能損害, 請優先幫忙解一下～

**Comment by x43x61x69** [comment]
@alieonsido 請幫忙處理一下，謝謝！

**Comment by x43x61x69** [comment]
這個 Issue 牽涉比較多東西，先移至下一個 milestone。

**Comment by x43x61x69** [comment]
- `write()` block：修正為只有在沒有於 `setup()` 內定義過時自動於 `setup()` 內加上 `attach()`。
- `attach()` block：修正為在沒有於 `setup()` 內定義過時於 `setup()` 內加上 `attach()`，否則於放置位置 overwrite。
