### ISSUE TITLE
Tone 有錯字

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#81]
![image](https://user-images.githubusercontent.com/23159280/27120178-3022dba0-5115-11e7-9fd1-7741fc6e999f.png)
應該是 B : Si

**Comment by x43x61x69** [comment]
不是誤植，Si 為義大利文，東亞和中歐地區習慣拼為 Si，英語系國家因為發音上會與 _C_ 調（Do）搞混故慣做 Ti：

[https://en.wikipedia.org/wiki/Solf%C3%A8ge#Major](https://en.wikipedia.org/wiki/Solf%C3%A8ge#Major)
[https://en.wikipedia.org/wiki/Talk%3ASolf%C3%A8ge#Ti_-_si.3F](https://en.wikipedia.org/wiki/Talk%3ASolf%C3%A8ge#Ti_-_si.3F)
