### ISSUE TITLE
使用正確的檔案名稱但無法另存新檔

### ISSUE THREAD

**Issue by bearwbearw** [MediaTek-Labs/BlocklyDuino-for-LinkIt#93]
![image](https://user-images.githubusercontent.com/23159280/27207848-62fc34f8-5274-11e7-9002-582b15eb15d3.png)

![image](https://user-images.githubusercontent.com/23159280/27207875-94440342-5274-11e7-988a-d96830b7174b.png)

A01_1
A01-1 
都不行

**Comment by x43x61x69** [comment]
原來的 RegEx pattern 有誤，只允許 0-9 和 A-z。

已新增空白、- 和 _。
